# Generated by Django 2.2.4 on 2020-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_join',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
