# Generated by Django 2.2.4 on 2020-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200930_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
