# Generated by Django 2.2.4 on 2020-10-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='night_work_frequency',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='self_dev',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='work_env',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='work_happyness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='work_hardness',
            field=models.IntegerField(default=3),
        ),
    ]
