# Generated by Django 2.2.4 on 2020-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutline',
            name='score',
            field=models.FloatField(),
        ),
    ]
